### ISSUE TITLE
Feature request: command to view all available roles

### ISSUE THREAD

**Issue by noiob** [benji7425/discord-bot-role-assigner#1]
just a nice quality-of life addition

**Comment by benji7425** [comment]
Not sure why I haven't thought of this yet... I will add it to my todo list and do my best to get around to it soon!

**Comment by benji7425** [comment]
This feature is developed, I will update the public installation of the bot to add this feature over the weekend.

**Comment by benji7425** [comment]
This feature has been added in v3.0.1, which has now been released!
You can view configured roles with `@Role_Assigner view-roles`, and there is a new `@Role_Assigner help` command as well!
Join my discord [here](discord.gg/SSkbwSJ) if you need more help :)
